### ISSUE TITLE
Check that parameter value is not null

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/error-reporting-java#15]
`quoteObject` throws a NullPointer when the parameter is null. 
It was in a test in my case, and it would be nice that null is allowed in such cases because now I have to mock quite a lot just to avoid NullPointer.

**Comment by jakobbraun** [comment]
:+1:

**Comment by AnastasiiaSergienko** [comment]
Update: unquotedParameter() also throws nullpointer
