### ISSUE TITLE
nullPointerException in unquotedParameter

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/error-reporting-java#17]
I think I already reported this problem, but I encountered it again: `nullPointerException` when the argument of unquotedParameter is null. Please validate the argument

**Comment by AnastasiiaSergienko** [comment]
I think it would be also nice if in case of null it appends "null" to the string. This happens in the tests when we mock exceptions and they don't have a message: 
 .unquotedParameter("cause", exception.getMessage())

**Comment by jakobbraun** [comment]
yes. It was fixed in 0.2.1. Please double-check that you're using the latest version

**Comment by AnastasiiaSergienko** [comment]
I'm using 0.2.1, I've just added it to the project, so it can't be a cache effect
