### ISSUE TITLE
Add forced quoting option

### ISSUE THREAD

**Issue by redcatbear** [exasol/error-reporting-java#27]
## Situation

We have automatic quoting and optional unquoted replacement. Generally for unknown object types not using quotes is fine. But there are exceptions. So forcing quotes with ``{{placeholder|q}}` would be useful.

## Acceptance Criteria

1. Forced quoting with `q` switch supported.

**Comment by morazow** [comment]
Yes, or by default quote all parameters and only skip quoting when `uq` is used.
